import { prisma } from '../db';
import { NcertDiscoveryService, NcertBookSeedDefinition } from '../services/ncertDiscovery.service';

export const OFFICIAL_NCERT_CATALOG: NcertBookSeedDefinition[] = [
  // ==========================================
  // CLASS 1
  // ==========================================
  {
    classNumber: 1,
    subject: 'Mathematics',
    bookName: 'Joyful Mathematics',
    bookNameHi: 'आनंदमय गणित',
    slug: 'class-1-joyful-mathematics-english',
    language: 'English',
    medium: 'English',
    edition: 'Latest NEP Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'aemh1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/aemh1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=0-13',
    chapterCount: 13,
    chapters: [
      { chapterNumber: 1, title: 'Finding the Furry Cat! (Pre-number Concepts)', titleHi: 'बिल्ली को ढूँढो!', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=1-13' },
      { chapterNumber: 2, title: 'What is Long? What is Round? (Shapes)', titleHi: 'क्या है लंबा? क्या है गोल?', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=2-13' },
      { chapterNumber: 3, title: 'Mango Treat (Numbers 1 to 9)', titleHi: 'आम की दावत (संख्याएँ 1 से 9)', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=3-13' },
      { chapterNumber: 4, title: 'Making 10 (Numbers 10 to 20)', titleHi: '10 बनाना (संख्याएँ 10 से 20)', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=4-13' },
      { chapterNumber: 5, title: 'How Many? (Addition)', titleHi: 'कितने? (जोड़)', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=5-13' },
      { chapterNumber: 6, title: 'Vegetable Farm (Subtraction)', titleHi: 'सब्जियों का बगीचा (घटाना)', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=6-13' },
      { chapterNumber: 7, title: 'Lina’s Family (Measurement)', titleHi: 'लीना का परिवार (मापन)', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=7-13' },
      { chapterNumber: 8, title: 'Fun with Numbers (Numbers 21 to 99)', titleHi: 'संख्याओं के साथ खेल', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=8-13' },
      { chapterNumber: 9, title: 'Utsav (Patterns)', titleHi: 'उत्सव (पैटर्न)', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=9-13' },
      { chapterNumber: 10, title: 'How do I Spend my Day? (Time)', titleHi: 'समय का हिसाब', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=10-13' },
      { chapterNumber: 11, title: 'How Many Times? (Multiplication)', titleHi: 'कितनी बार?', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=11-13' },
      { chapterNumber: 12, title: 'How Much Can We Spend? (Money)', titleHi: 'पैसे और खरीदारी', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=12-13' },
      { chapterNumber: 13, title: 'So Many Toys! (Data Handling)', titleHi: 'इतने सारे खिलौने!', pdfUrl: 'https://ncert.nic.in/textbook.php?aemh1=13-13' },
    ],
  },
  {
    classNumber: 1,
    subject: 'Mathematics',
    bookName: 'आनंदमय गणित',
    bookNameHi: 'आनंदमय गणित',
    slug: 'class-1-anandmay-ganit-hindi',
    language: 'Hindi',
    medium: 'Hindi',
    edition: 'Latest NEP Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'ahmh1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/ahmh1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?ahmh1=0-13',
    chapterCount: 13,
    chapters: [
      { chapterNumber: 1, title: 'बिल्ली को ढूँढो! (संख्या-पूर्व अवधारणाएँ)', pdfUrl: 'https://ncert.nic.in/textbook.php?ahmh1=1-13' },
      { chapterNumber: 2, title: 'क्या है लंबा? क्या है गोल? (आकृतियाँ)', pdfUrl: 'https://ncert.nic.in/textbook.php?ahmh1=2-13' },
      { chapterNumber: 3, title: 'आम की दावत (संख्याएँ 1 से 9)', pdfUrl: 'https://ncert.nic.in/textbook.php?ahmh1=3-13' },
      { chapterNumber: 4, title: '10 बनाना (संख्याएँ 10 से 20)', pdfUrl: 'https://ncert.nic.in/textbook.php?ahmh1=4-13' },
      { chapterNumber: 5, title: 'कितने? (जोड़)', pdfUrl: 'https://ncert.nic.in/textbook.php?ahmh1=5-13' },
    ],
  },
  {
    classNumber: 1,
    subject: 'Hindi',
    bookName: 'Sarangi (सारंगी)',
    bookNameHi: 'सारंगी',
    slug: 'class-1-sarangi-hindi',
    language: 'Hindi',
    medium: 'Hindi',
    edition: 'Latest NEP Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'ahhn1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/ahhn1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?ahhn1=0-19',
    chapterCount: 19,
    chapters: [
      { chapterNumber: 1, title: 'मीना का परिवार', pdfUrl: 'https://ncert.nic.in/textbook.php?ahhn1=1-19' },
      { chapterNumber: 2, title: 'दादा-दादी', pdfUrl: 'https://ncert.nic.in/textbook.php?ahhn1=2-19' },
      { chapterNumber: 3, title: 'रीना का घर', pdfUrl: 'https://ncert.nic.in/textbook.php?ahhn1=3-19' },
    ],
  },
  {
    classNumber: 1,
    subject: 'English',
    bookName: 'Mridang',
    bookNameHi: 'मृदंग',
    slug: 'class-1-mridang-english',
    language: 'English',
    medium: 'English',
    edition: 'Latest NEP Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'aeen1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/aeen1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?aeen1=0-9',
    chapterCount: 9,
    chapters: [
      { chapterNumber: 1, title: 'Two Little Hands', pdfUrl: 'https://ncert.nic.in/textbook.php?aeen1=1-9' },
      { chapterNumber: 2, title: 'Greetings', pdfUrl: 'https://ncert.nic.in/textbook.php?aeen1=2-9' },
    ],
  },

  // ==========================================
  // CLASS 6
  // ==========================================
  {
    classNumber: 6,
    subject: 'Mathematics',
    bookName: 'Ganita Prakash',
    bookNameHi: 'गणित प्रकाश',
    slug: 'class-6-ganita-prakash-mathematics',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'femh1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/femh1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?femh1=0-10',
    chapterCount: 10,
    chapters: [
      { chapterNumber: 1, title: 'Patterns in Mathematics', titleHi: 'गणित में पैटर्न', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=1-10' },
      { chapterNumber: 2, title: 'Lines and Angles', titleHi: 'रेखाएँ और कोण', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=2-10' },
      { chapterNumber: 3, title: 'Number Play', titleHi: 'संख्याओं का खेल', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=3-10' },
      { chapterNumber: 4, title: 'Data Handling and Presentation', titleHi: 'आँकड़ों का प्रबंधन', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=4-10' },
      { chapterNumber: 5, title: 'Prime Time', titleHi: 'अभाज्य संख्याएँ', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=5-10' },
      { chapterNumber: 6, title: 'Perimeter and Area', titleHi: 'परिमाप और क्षेत्रफल', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=6-10' },
      { chapterNumber: 7, title: 'Fractions', titleHi: 'भिन्न', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=7-10' },
      { chapterNumber: 8, title: 'Playing with Constructions', titleHi: 'रचनाओं के साथ खेल', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=8-10' },
      { chapterNumber: 9, title: 'Symmetry', titleHi: 'सममिति', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=9-10' },
      { chapterNumber: 10, title: 'The Other Side of Zero (Negative Numbers)', titleHi: 'ऋणात्मक संख्याएँ', pdfUrl: 'https://ncert.nic.in/textbook.php?femh1=10-10' },
    ],
  },
  {
    classNumber: 6,
    subject: 'Science',
    bookName: 'Curiosity',
    bookNameHi: 'जिज्ञासा (विज्ञान)',
    slug: 'class-6-curiosity-science',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'fesc1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/fesc1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=0-12',
    chapterCount: 12,
    chapters: [
      { chapterNumber: 1, title: 'The Wonderful World of Science', titleHi: 'विज्ञान की अद्भुत दुनिया', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=1-12' },
      { chapterNumber: 2, title: 'Diversity in the Living World', titleHi: 'सजीव जगत में विविधता', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=2-12' },
      { chapterNumber: 3, title: 'Mindful Eating: A Path to a Healthy Body', titleHi: 'उचित पोषण और स्वास्थ्य', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=3-12' },
      { chapterNumber: 4, title: 'Exploring Magnets', titleHi: 'चुंबकों की खोज', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=4-12' },
      { chapterNumber: 5, title: 'Measurement of Length and Motion', titleHi: 'दूरी और गति का मापन', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=5-12' },
      { chapterNumber: 6, title: 'Materials Around Us', titleHi: 'हमारे चारों ओर के पदार्थ', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=6-12' },
      { chapterNumber: 7, title: 'Temperature and Its Measurement', titleHi: 'तापमान और उसका मापन', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=7-12' },
      { chapterNumber: 8, title: 'A Journey through States of Water', titleHi: 'जल की अवस्थाओं की यात्रा', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=8-12' },
      { chapterNumber: 9, title: 'Methods of Separation in Everyday Life', titleHi: 'पृथक्करण की विधियाँ', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=9-12' },
      { chapterNumber: 10, title: 'Living Creatures: Exploring their Characteristics', titleHi: 'सजीवों के लक्षण', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=10-12' },
      { chapterNumber: 11, title: 'Nature’s Treasures', titleHi: 'प्रकृति के उपहार', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=11-12' },
      { chapterNumber: 12, title: 'Beyond Earth', titleHi: 'पृथ्वी से परे', pdfUrl: 'https://ncert.nic.in/textbook.php?fesc1=12-12' },
    ],
  },
  {
    classNumber: 6,
    subject: 'Science',
    bookName: 'जिज्ञासा (विज्ञान)',
    bookNameHi: 'जिज्ञासा (विज्ञान)',
    slug: 'class-6-jigyasa-vigyan-hindi',
    language: 'Hindi',
    medium: 'Hindi',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'fhsc1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/fhsc1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?fhsc1=0-12',
    chapterCount: 12,
    chapters: [
      { chapterNumber: 1, title: 'विज्ञान की अद्भुत दुनिया', pdfUrl: 'https://ncert.nic.in/textbook.php?fhsc1=1-12' },
      { chapterNumber: 2, title: 'सजीव जगत में विविधता', pdfUrl: 'https://ncert.nic.in/textbook.php?fhsc1=2-12' },
      { chapterNumber: 3, title: 'उचित खान-पान: स्वस्थ शरीर का आधार', pdfUrl: 'https://ncert.nic.in/textbook.php?fhsc1=3-12' },
    ],
  },
  {
    classNumber: 6,
    subject: 'Social Science',
    bookName: 'Exploring Society: India and Beyond',
    bookNameHi: 'समाज और हमारा परिवेश',
    slug: 'class-6-exploring-society-social-science',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'fess1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/fess1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?fess1=0-15',
    chapterCount: 15,
    chapters: [
      { chapterNumber: 1, title: 'Locating Places on the Earth', titleHi: 'पृथ्वी पर स्थानों का निर्धारण', pdfUrl: 'https://ncert.nic.in/textbook.php?fess1=1-15' },
      { chapterNumber: 2, title: 'Oceans and Continents', titleHi: 'महासागर और महाद्वीप', pdfUrl: 'https://ncert.nic.in/textbook.php?fess1=2-15' },
      { chapterNumber: 3, title: 'Landforms and Life', titleHi: 'स्थलरूप और जीवन', pdfUrl: 'https://ncert.nic.in/textbook.php?fess1=3-15' },
    ],
  },

  // ==========================================
  // CLASS 9
  // ==========================================
  {
    classNumber: 9,
    subject: 'Science',
    bookName: 'Science',
    bookNameHi: 'विज्ञान',
    slug: 'class-9-science-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'iesc1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/iesc1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=0-12',
    chapterCount: 12,
    chapters: [
      { chapterNumber: 1, title: 'Matter in Our Surroundings', titleHi: 'हमारे आस-पास के पदार्थ', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=1-12' },
      { chapterNumber: 2, title: 'Is Matter Around Us Pure?', titleHi: 'क्या हमारे आस-पास के पदार्थ शुद्ध हैं?', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=2-12' },
      { chapterNumber: 3, title: 'Atoms and Molecules', titleHi: 'परमाणु एवं अणु', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=3-12' },
      { chapterNumber: 4, title: 'Structure of the Atom', titleHi: 'परमाणु की संरचना', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=4-12' },
      { chapterNumber: 5, title: 'The Fundamental Unit of Life', titleHi: 'जीवन की मौलिक इकाई', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=5-12' },
      { chapterNumber: 6, title: 'Tissues', titleHi: 'ऊतक', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=6-12' },
      { chapterNumber: 7, title: 'Motion', titleHi: 'गति', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=7-12' },
      { chapterNumber: 8, title: 'Force and Laws of Motion', titleHi: 'बल तथा गति के नियम', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=8-12' },
      { chapterNumber: 9, title: 'Gravitation', titleHi: 'गुरुत्वाकर्षण', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=9-12' },
      { chapterNumber: 10, title: 'Work and Energy', titleHi: 'कार्य तथा ऊर्जा', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=10-12' },
      { chapterNumber: 11, title: 'Sound', titleHi: 'ध्वनि', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=11-12' },
      { chapterNumber: 12, title: 'Improvement in Food Resources', titleHi: 'खाद्य संसाधनों में सुधार', pdfUrl: 'https://ncert.nic.in/textbook.php?iesc1=12-12' },
    ],
  },
  {
    classNumber: 9,
    subject: 'Mathematics',
    bookName: 'Mathematics',
    bookNameHi: 'गणित',
    slug: 'class-9-mathematics-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'iemh1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/iemh1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=0-12',
    chapterCount: 12,
    chapters: [
      { chapterNumber: 1, title: 'Number Systems', titleHi: 'संख्या पद्धति', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=1-12' },
      { chapterNumber: 2, title: 'Polynomials', titleHi: 'बहुपद', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=2-12' },
      { chapterNumber: 3, title: 'Coordinate Geometry', titleHi: 'निर्देशांक ज्यामिति', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=3-12' },
      { chapterNumber: 4, title: 'Linear Equations in Two Variables', titleHi: 'दो चरों वाले रैखिक समीकरण', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=4-12' },
      { chapterNumber: 5, title: 'Introduction to Euclid’s Geometry', titleHi: 'यूक्लिड की ज्यामिति का परिचय', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=5-12' },
      { chapterNumber: 6, title: 'Lines and Angles', titleHi: 'रेखाएँ और कोण', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=6-12' },
      { chapterNumber: 7, title: 'Triangles', titleHi: 'त्रिभुज', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=7-12' },
      { chapterNumber: 8, title: 'Quadrilaterals', titleHi: 'चतुर्भुज', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=8-12' },
      { chapterNumber: 9, title: 'Circles', titleHi: 'वृत्त', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=9-12' },
      { chapterNumber: 10, title: 'Heron’s Formula', titleHi: 'हीरोन का सूत्र', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=10-12' },
      { chapterNumber: 11, title: 'Surface Areas and Volumes', titleHi: 'पृष्ठीय क्षेत्रफल और आयतन', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=11-12' },
      { chapterNumber: 12, title: 'Statistics', titleHi: 'सांख्यिकी', pdfUrl: 'https://ncert.nic.in/textbook.php?iemh1=12-12' },
    ],
  },
  {
    classNumber: 9,
    subject: 'English',
    bookName: 'Beehive (Textbook)',
    bookNameHi: 'बिहाइव',
    slug: 'class-9-beehive-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'iebe1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/iebe1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?iebe1=0-9',
    chapterCount: 9,
    chapters: [
      { chapterNumber: 1, title: 'The Fun They Had', pdfUrl: 'https://ncert.nic.in/textbook.php?iebe1=1-9' },
      { chapterNumber: 2, title: 'The Sound of Music', pdfUrl: 'https://ncert.nic.in/textbook.php?iebe1=2-9' },
      { chapterNumber: 3, title: 'The Little Girl', pdfUrl: 'https://ncert.nic.in/textbook.php?iebe1=3-9' },
    ],
  },
  {
    classNumber: 9,
    subject: 'Hindi',
    bookName: 'Kshitij (क्षितिज भाग-१)',
    bookNameHi: 'क्षितिज भाग-१',
    slug: 'class-9-kshitij-hindi',
    language: 'Hindi',
    medium: 'Hindi',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'ihks1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/ihks1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?ihks1=0-14',
    chapterCount: 14,
    chapters: [
      { chapterNumber: 1, title: 'दो बैलों की कथा (प्रेमचंद)', pdfUrl: 'https://ncert.nic.in/textbook.php?ihks1=1-14' },
      { chapterNumber: 2, title: 'ल्हासा की ओर (राहुल सांकृत्यायन)', pdfUrl: 'https://ncert.nic.in/textbook.php?ihks1=2-14' },
    ],
  },

  // ==========================================
  // CLASS 10
  // ==========================================
  {
    classNumber: 10,
    subject: 'Science',
    bookName: 'Science',
    bookNameHi: 'विज्ञान',
    slug: 'class-10-science-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'jesc1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/jesc1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=0-13',
    chapterCount: 13,
    chapters: [
      { chapterNumber: 1, title: 'Chemical Reactions and Equations', titleHi: 'रासायनिक अभिक्रियाएँ एवं समीकरण', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=1-13' },
      { chapterNumber: 2, title: 'Acids, Bases and Salts', titleHi: 'अम्ल, क्षारक एवं लवण', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=2-13' },
      { chapterNumber: 3, title: 'Metals and Non-metals', titleHi: 'धातु एवं अधातु', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=3-13' },
      { chapterNumber: 4, title: 'Carbon and its Compounds', titleHi: 'कार्बन एवं उसके यौगिक', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=4-13' },
      { chapterNumber: 5, title: 'Life Processes', titleHi: 'जैव प्रक्रम', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=5-13' },
      { chapterNumber: 6, title: 'Control and Coordination', titleHi: 'नियंत्रण एवं समन्वय', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=6-13' },
      { chapterNumber: 7, title: 'How do Organisms Reproduce?', titleHi: 'जीव जनन कैसे करते हैं?', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=7-13' },
      { chapterNumber: 8, title: 'Heredity and Evolution', titleHi: 'आनुवंशिकता एवं जैव विकास', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=8-13' },
      { chapterNumber: 9, title: 'Light – Reflection and Refraction', titleHi: 'प्रकाश – परावर्तन तथा अपवर्तन', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=9-13' },
      { chapterNumber: 10, title: 'The Human Eye and the Colourful World', titleHi: 'मानव नेत्र तथा रंगबिरंगा संसार', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=10-13' },
      { chapterNumber: 11, title: 'Electricity', titleHi: 'विद्युत', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=11-13' },
      { chapterNumber: 12, title: 'Magnetic Effects of Electric Current', titleHi: 'विद्युत धारा के चुंबकीय प्रभाव', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=12-13' },
      { chapterNumber: 13, title: 'Our Environment', titleHi: 'हमारा पर्यावरण', pdfUrl: 'https://ncert.nic.in/textbook.php?jesc1=13-13' },
    ],
  },
  {
    classNumber: 10,
    subject: 'Science',
    bookName: 'विज्ञान',
    bookNameHi: 'विज्ञान',
    slug: 'class-10-vigyan-hindi',
    language: 'Hindi',
    medium: 'Hindi',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'jhsc1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/jhsc1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?jhsc1=0-13',
    chapterCount: 13,
    chapters: [
      { chapterNumber: 1, title: 'रासायनिक अभिक्रियाएँ एवं समीकरण', pdfUrl: 'https://ncert.nic.in/textbook.php?jhsc1=1-13' },
      { chapterNumber: 2, title: 'अम्ल, क्षारक एवं लवण', pdfUrl: 'https://ncert.nic.in/textbook.php?jhsc1=2-13' },
      { chapterNumber: 3, title: 'धातु एवं अधातु', pdfUrl: 'https://ncert.nic.in/textbook.php?jhsc1=3-13' },
      { chapterNumber: 4, title: 'कार्बन एवं उसके यौगिक', pdfUrl: 'https://ncert.nic.in/textbook.php?jhsc1=4-13' },
      { chapterNumber: 5, title: 'जैव प्रक्रम', pdfUrl: 'https://ncert.nic.in/textbook.php?jhsc1=5-13' },
    ],
  },
  {
    classNumber: 10,
    subject: 'Mathematics',
    bookName: 'Mathematics',
    bookNameHi: 'गणित',
    slug: 'class-10-mathematics-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'jemh1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/jemh1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=0-14',
    chapterCount: 14,
    chapters: [
      { chapterNumber: 1, title: 'Real Numbers', titleHi: 'वास्तविक संख्याएँ', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=1-14' },
      { chapterNumber: 2, title: 'Polynomials', titleHi: 'बहुपद', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=2-14' },
      { chapterNumber: 3, title: 'Pair of Linear Equations in Two Variables', titleHi: 'दो चर वाले रैखिक समीकरण युग्म', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=3-14' },
      { chapterNumber: 4, title: 'Quadratic Equations', titleHi: 'द्विघात समीकरण', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=4-14' },
      { chapterNumber: 5, title: 'Arithmetic Progressions', titleHi: 'समांतर श्रेढ़ियाँ', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=5-14' },
      { chapterNumber: 6, title: 'Triangles', titleHi: 'त्रिभुज', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=6-14' },
      { chapterNumber: 7, title: 'Coordinate Geometry', titleHi: 'निर्देशांक ज्यामिति', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=7-14' },
      { chapterNumber: 8, title: 'Introduction to Trigonometry', titleHi: 'त्रिकोणमिति का परिचय', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=8-14' },
      { chapterNumber: 9, title: 'Some Applications of Trigonometry', titleHi: 'त्रिकोणमिति के कुछ अनुप्रयोग', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=9-14' },
      { chapterNumber: 10, title: 'Circles', titleHi: 'वृत्त', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=10-14' },
      { chapterNumber: 11, title: 'Areas Related to Circles', titleHi: 'वृत्तों से संबंधित क्षेत्रफल', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=11-14' },
      { chapterNumber: 12, title: 'Surface Areas and Volumes', titleHi: 'पृष्ठीय क्षेत्रफल और आयतन', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=12-14' },
      { chapterNumber: 13, title: 'Statistics', titleHi: 'सांख्यिकी', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=13-14' },
      { chapterNumber: 14, title: 'Probability', titleHi: 'प्रायिकता', pdfUrl: 'https://ncert.nic.in/textbook.php?jemh1=14-14' },
    ],
  },
  {
    classNumber: 10,
    subject: 'Social Science',
    bookName: 'Democratic Politics - II',
    bookNameHi: 'लोकतांत्रिक राजनीति - II',
    slug: 'class-10-democratic-politics-ii',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'jess3',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/jess3cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?jess3=0-8',
    chapterCount: 8,
    chapters: [
      { chapterNumber: 1, title: 'Power Sharing', titleHi: 'सत्ता की साझेदारी', pdfUrl: 'https://ncert.nic.in/textbook.php?jess3=1-8' },
      { chapterNumber: 2, title: 'Federalism', titleHi: 'संघवाद', pdfUrl: 'https://ncert.nic.in/textbook.php?jess3=2-8' },
      { chapterNumber: 3, title: 'Gender, Religion and Caste', titleHi: 'लिंग, धर्म और जाति', pdfUrl: 'https://ncert.nic.in/textbook.php?jess3=3-8' },
      { chapterNumber: 4, title: 'Political Parties', titleHi: 'राजनीतिक दल', pdfUrl: 'https://ncert.nic.in/textbook.php?jess3=4-8' },
      { chapterNumber: 5, title: 'Outcomes of Democracy', titleHi: 'लोकतंत्र के परिणाम', pdfUrl: 'https://ncert.nic.in/textbook.php?jess3=5-8' },
    ],
  },
  {
    classNumber: 10,
    subject: 'English',
    bookName: 'First Flight',
    bookNameHi: 'फर्स्ट फ्लाइट',
    slug: 'class-10-first-flight-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'jeff1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/jeff1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?jeff1=0-9',
    chapterCount: 9,
    chapters: [
      { chapterNumber: 1, title: 'A Letter to God', pdfUrl: 'https://ncert.nic.in/textbook.php?jeff1=1-9' },
      { chapterNumber: 2, title: 'Nelson Mandela: Long Walk to Freedom', pdfUrl: 'https://ncert.nic.in/textbook.php?jeff1=2-9' },
      { chapterNumber: 3, title: 'Two Stories about Flying', pdfUrl: 'https://ncert.nic.in/textbook.php?jeff1=3-9' },
    ],
  },

  // ==========================================
  // CLASS 11
  // ==========================================
  {
    classNumber: 11,
    subject: 'Physics',
    bookName: 'Physics Part - I',
    bookNameHi: 'भौतिकी भाग - १',
    slug: 'class-11-physics-part-1-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'keph1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/keph1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?keph1=0-7',
    chapterCount: 7,
    chapters: [
      { chapterNumber: 1, title: 'Units and Measurements', titleHi: 'मात्रक और मापन', pdfUrl: 'https://ncert.nic.in/textbook.php?keph1=1-7' },
      { chapterNumber: 2, title: 'Motion in a Straight Line', titleHi: 'सरल रेखा में गति', pdfUrl: 'https://ncert.nic.in/textbook.php?keph1=2-7' },
      { chapterNumber: 3, title: 'Motion in a Plane', titleHi: 'समतल में गति', pdfUrl: 'https://ncert.nic.in/textbook.php?keph1=3-7' },
      { chapterNumber: 4, title: 'Laws of Motion', titleHi: 'गति के नियम', pdfUrl: 'https://ncert.nic.in/textbook.php?keph1=4-7' },
      { chapterNumber: 5, title: 'Work, Energy and Power', titleHi: 'कार्य, ऊर्जा और शक्ति', pdfUrl: 'https://ncert.nic.in/textbook.php?keph1=5-7' },
      { chapterNumber: 6, title: 'System of Particles and Rotational Motion', titleHi: 'कणों के निकाय तथा घूर्णी गति', pdfUrl: 'https://ncert.nic.in/textbook.php?keph1=6-7' },
      { chapterNumber: 7, title: 'Gravitation', titleHi: 'गुरुत्वाकर्षण', pdfUrl: 'https://ncert.nic.in/textbook.php?keph1=7-7' },
    ],
  },
  {
    classNumber: 11,
    subject: 'Chemistry',
    bookName: 'Chemistry Part - I',
    bookNameHi: 'रसायन विज्ञान भाग - १',
    slug: 'class-11-chemistry-part-1-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'kech1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/kech1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?kech1=0-6',
    chapterCount: 6,
    chapters: [
      { chapterNumber: 1, title: 'Some Basic Concepts of Chemistry', titleHi: 'रसायन विज्ञान की कुछ मूल अवधारणाएँ', pdfUrl: 'https://ncert.nic.in/textbook.php?kech1=1-6' },
      { chapterNumber: 2, title: 'Structure of Atom', titleHi: 'परमाणु की संरचना', pdfUrl: 'https://ncert.nic.in/textbook.php?kech1=2-6' },
      { chapterNumber: 3, title: 'Classification of Elements and Periodicity in Properties', titleHi: 'तत्वों का वर्गीकरण एवं गुणधर्मों में आवर्तिता', pdfUrl: 'https://ncert.nic.in/textbook.php?kech1=3-6' },
      { chapterNumber: 4, title: 'Chemical Bonding and Molecular Structure', titleHi: 'रासायनिक आबंधन तथा आण्विक संरचना', pdfUrl: 'https://ncert.nic.in/textbook.php?kech1=4-6' },
      { chapterNumber: 5, title: 'Thermodynamics', titleHi: 'ऊष्मागतिकी', pdfUrl: 'https://ncert.nic.in/textbook.php?kech1=5-6' },
      { chapterNumber: 6, title: 'Equilibrium', titleHi: 'साम्यावस्था', pdfUrl: 'https://ncert.nic.in/textbook.php?kech1=6-6' },
    ],
  },
  {
    classNumber: 11,
    subject: 'Biology',
    bookName: 'Biology',
    bookNameHi: 'जीव विज्ञान',
    slug: 'class-11-biology-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'kebo1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/kebo1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?kebo1=0-19',
    chapterCount: 19,
    chapters: [
      { chapterNumber: 1, title: 'The Living World', titleHi: 'जीव जगत', pdfUrl: 'https://ncert.nic.in/textbook.php?kebo1=1-19' },
      { chapterNumber: 2, title: 'Biological Classification', titleHi: 'जीव जगत का वर्गीकरण', pdfUrl: 'https://ncert.nic.in/textbook.php?kebo1=2-19' },
      { chapterNumber: 3, title: 'Plant Kingdom', titleHi: 'वनस्पति जगत', pdfUrl: 'https://ncert.nic.in/textbook.php?kebo1=3-19' },
      { chapterNumber: 4, title: 'Animal Kingdom', titleHi: 'प्राणी जगत', pdfUrl: 'https://ncert.nic.in/textbook.php?kebo1=4-19' },
    ],
  },
  {
    classNumber: 11,
    subject: 'Mathematics',
    bookName: 'Mathematics',
    bookNameHi: 'गणित',
    slug: 'class-11-mathematics-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'kemh1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/kemh1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?kemh1=0-14',
    chapterCount: 14,
    chapters: [
      { chapterNumber: 1, title: 'Sets', titleHi: 'समुच्चय', pdfUrl: 'https://ncert.nic.in/textbook.php?kemh1=1-14' },
      { chapterNumber: 2, title: 'Relations and Functions', titleHi: 'संबंध एवं फलन', pdfUrl: 'https://ncert.nic.in/textbook.php?kemh1=2-14' },
      { chapterNumber: 3, title: 'Trigonometric Functions', titleHi: 'त्रिकोणमितीय फलन', pdfUrl: 'https://ncert.nic.in/textbook.php?kemh1=3-14' },
    ],
  },

  // ==========================================
  // CLASS 12
  // ==========================================
  {
    classNumber: 12,
    subject: 'Physics',
    bookName: 'Physics Part - I',
    bookNameHi: 'भौतिकी भाग - १',
    slug: 'class-12-physics-part-1-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'leph1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/leph1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?leph1=0-8',
    chapterCount: 8,
    chapters: [
      { chapterNumber: 1, title: 'Electric Charges and Fields', titleHi: 'वैद्युत आवेश तथा क्षेत्र', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=1-8' },
      { chapterNumber: 2, title: 'Electrostatic Potential and Capacitance', titleHi: 'स्थिरवैद्युत विभव तथा धारिता', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=2-8' },
      { chapterNumber: 3, title: 'Current Electricity', titleHi: 'विद्युत धारा', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=3-8' },
      { chapterNumber: 4, title: 'Moving Charges and Magnetism', titleHi: 'गतिमान आवेश और चुंबकत्व', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=4-8' },
      { chapterNumber: 5, title: 'Magnetism and Matter', titleHi: 'चुंबकत्व एवं द्रव्य', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=5-8' },
      { chapterNumber: 6, title: 'Electromagnetic Induction', titleHi: 'वैद्युतचुंबकीय प्रेरण', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=6-8' },
      { chapterNumber: 7, title: 'Alternating Current', titleHi: 'प्रत्यावर्ती धारा', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=7-8' },
      { chapterNumber: 8, title: 'Electromagnetic Waves', titleHi: 'वैद्युतचुंबकीय तरंगें', pdfUrl: 'https://ncert.nic.in/textbook.php?leph1=8-8' },
    ],
  },
  {
    classNumber: 12,
    subject: 'Physics',
    bookName: 'Physics Part - II',
    bookNameHi: 'भौतिकी भाग - २',
    slug: 'class-12-physics-part-2-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'leph2',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/leph2cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?leph2=0-6',
    chapterCount: 6,
    chapters: [
      { chapterNumber: 9, title: 'Ray Optics and Optical Instruments', titleHi: 'किरण प्रकाशिकी एवं प्रकाशिक यंत्र', pdfUrl: 'https://ncert.nic.in/textbook.php?leph2=1-6' },
      { chapterNumber: 10, title: 'Wave Optics', titleHi: 'तरंग-प्रकाशिकी', pdfUrl: 'https://ncert.nic.in/textbook.php?leph2=2-6' },
      { chapterNumber: 11, title: 'Dual Nature of Radiation and Matter', titleHi: 'विकिरण तथा द्रव्य की द्वैत प्रकृति', pdfUrl: 'https://ncert.nic.in/textbook.php?leph2=3-6' },
      { chapterNumber: 12, title: 'Atoms', titleHi: 'परमाणु', pdfUrl: 'https://ncert.nic.in/textbook.php?leph2=4-6' },
      { chapterNumber: 13, title: 'Nuclei', titleHi: 'नाभिक', pdfUrl: 'https://ncert.nic.in/textbook.php?leph2=5-6' },
      { chapterNumber: 14, title: 'Semiconductor Electronics: Materials, Devices and Simple Circuits', titleHi: 'अर्धचालक इलेक्ट्रॉनिकी', pdfUrl: 'https://ncert.nic.in/textbook.php?leph2=6-6' },
    ],
  },
  {
    classNumber: 12,
    subject: 'Chemistry',
    bookName: 'Chemistry Part - I',
    bookNameHi: 'रसायन विज्ञान भाग - १',
    slug: 'class-12-chemistry-part-1-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'lech1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/lech1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?lech1=0-5',
    chapterCount: 5,
    chapters: [
      { chapterNumber: 1, title: 'Solutions', titleHi: 'विलयन', pdfUrl: 'https://ncert.nic.in/textbook.php?lech1=1-5' },
      { chapterNumber: 2, title: 'Electrochemistry', titleHi: 'वैद्युतरसायन', pdfUrl: 'https://ncert.nic.in/textbook.php?lech1=2-5' },
      { chapterNumber: 3, title: 'Chemical Kinetics', titleHi: 'रासायनिक बलगतिकी', pdfUrl: 'https://ncert.nic.in/textbook.php?lech1=3-5' },
      { chapterNumber: 4, title: 'The d- and f-Block Elements', titleHi: 'd- एवं f-ब्लॉक के तत्व', pdfUrl: 'https://ncert.nic.in/textbook.php?lech1=4-5' },
      { chapterNumber: 5, title: 'Coordination Compounds', titleHi: 'उपसहसंयोजन यौगिक', pdfUrl: 'https://ncert.nic.in/textbook.php?lech1=5-5' },
    ],
  },
  {
    classNumber: 12,
    subject: 'Chemistry',
    bookName: 'Chemistry Part - II',
    bookNameHi: 'रसायन विज्ञान भाग - २',
    slug: 'class-12-chemistry-part-2-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'lech2',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/lech2cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?lech2=0-5',
    chapterCount: 5,
    chapters: [
      { chapterNumber: 6, title: 'Haloalkanes and Haloarenes', titleHi: 'हैलोऐल्केन तथा हैलोऐरीन', pdfUrl: 'https://ncert.nic.in/textbook.php?lech2=1-5' },
      { chapterNumber: 7, title: 'Alcohols, Phenols and Ethers', titleHi: 'ऐल्कोहॉल, फ़ीनॉल एवं ईथर', pdfUrl: 'https://ncert.nic.in/textbook.php?lech2=2-5' },
      { chapterNumber: 8, title: 'Aldehydes, Ketones and Carboxylic Acids', titleHi: 'ऐल्डिहाइड, कीटोन एवं कार्बोक्सिलिक अम्ल', pdfUrl: 'https://ncert.nic.in/textbook.php?lech2=3-5' },
      { chapterNumber: 9, title: 'Amines', titleHi: 'ऐमीन', pdfUrl: 'https://ncert.nic.in/textbook.php?lech2=4-5' },
      { chapterNumber: 10, title: 'Biomolecules', titleHi: 'जैव-अणु', pdfUrl: 'https://ncert.nic.in/textbook.php?lech2=5-5' },
    ],
  },
  {
    classNumber: 12,
    subject: 'Biology',
    bookName: 'Biology',
    bookNameHi: 'जीव विज्ञान',
    slug: 'class-12-biology-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'lebo1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/lebo1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?lebo1=0-13',
    chapterCount: 13,
    chapters: [
      { chapterNumber: 1, title: 'Sexual Reproduction in Flowering Plants', titleHi: 'पुष्पी पादपों में लैंगिक जनन', pdfUrl: 'https://ncert.nic.in/textbook.php?lebo1=1-13' },
      { chapterNumber: 2, title: 'Human Reproduction', titleHi: 'मानव जनन', pdfUrl: 'https://ncert.nic.in/textbook.php?lebo1=2-13' },
      { chapterNumber: 3, title: 'Reproductive Health', titleHi: 'जनन स्वास्थ्य', pdfUrl: 'https://ncert.nic.in/textbook.php?lebo1=3-13' },
      { chapterNumber: 4, title: 'Principles of Inheritance and Variation', titleHi: 'वंशागति तथा विविधता के सिद्धांत', pdfUrl: 'https://ncert.nic.in/textbook.php?lebo1=4-13' },
      { chapterNumber: 5, title: 'Molecular Basis of Inheritance', titleHi: 'वंशागति के आण्विक आधार', pdfUrl: 'https://ncert.nic.in/textbook.php?lebo1=5-13' },
    ],
  },
  {
    classNumber: 12,
    subject: 'Mathematics',
    bookName: 'Mathematics Part - I',
    bookNameHi: 'गणित भाग - १',
    slug: 'class-12-mathematics-part-1-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'lemh1',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/lemh1cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?lemh1=0-6',
    chapterCount: 6,
    chapters: [
      { chapterNumber: 1, title: 'Relations and Functions', titleHi: 'संबंध एवं फलन', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh1=1-6' },
      { chapterNumber: 2, title: 'Inverse Trigonometric Functions', titleHi: 'प्रतिलोम त्रिकोणमितीय फलन', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh1=2-6' },
      { chapterNumber: 3, title: 'Matrices', titleHi: 'आव्यूह', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh1=3-6' },
      { chapterNumber: 4, title: 'Determinants', titleHi: 'सारणिक', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh1=4-6' },
      { chapterNumber: 5, title: 'Continuity and Differentiability', titleHi: 'सांतत्य तथा अवकलनीयता', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh1=5-6' },
      { chapterNumber: 6, title: 'Application of Derivatives', titleHi: 'अवकलज के अनुप्रयोग', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh1=6-6' },
    ],
  },
  {
    classNumber: 12,
    subject: 'Mathematics',
    bookName: 'Mathematics Part - II',
    bookNameHi: 'गणित भाग - २',
    slug: 'class-12-mathematics-part-2-english',
    language: 'English',
    medium: 'English',
    edition: 'Rationalised Edition 2025-26',
    academicYear: '2025-26',
    bookCode: 'lemh2',
    coverImageUrl: 'https://ncert.nic.in/textbook/pdf/lemh2cc.jpg',
    officialPageUrl: 'https://ncert.nic.in/textbook.php',
    officialPdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=0-7',
    chapterCount: 7,
    chapters: [
      { chapterNumber: 7, title: 'Integrals', titleHi: 'समाकलन', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=1-7' },
      { chapterNumber: 8, title: 'Application of Integrals', titleHi: 'समाकलनों के अनुप्रयोग', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=2-7' },
      { chapterNumber: 9, title: 'Differential Equations', titleHi: 'अवकल समीकरण', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=3-7' },
      { chapterNumber: 10, title: 'Vector Algebra', titleHi: 'सदिश बीजगणित', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=4-7' },
      { chapterNumber: 11, title: 'Three Dimensional Geometry', titleHi: 'त्रि-विमीय ज्यामिति', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=5-7' },
      { chapterNumber: 12, title: 'Linear Programming', titleHi: 'रैखिक प्रोग्रामन', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=6-7' },
      { chapterNumber: 13, title: 'Probability', titleHi: 'प्रायिकता', pdfUrl: 'https://ncert.nic.in/textbook.php?lemh2=7-7' },
    ],
  },
];

export async function seedNcertCatalog() {
  console.log('📚 Seeding Official NCERT Textbooks Catalogue...');

  let count = 0;
  for (const book of OFFICIAL_NCERT_CATALOG) {
    await (prisma as any).ncertBook.upsert({
      where: { slug: book.slug },
      update: {
        classNumber: book.classNumber,
        subject: book.subject,
        bookName: book.bookName,
        bookNameHi: book.bookNameHi,
        language: book.language,
        medium: book.medium,
        edition: book.edition,
        academicYear: book.academicYear,
        bookCode: book.bookCode,
        coverImageUrl: book.coverImageUrl,
        officialPageUrl: book.officialPageUrl,
        officialPdfUrl: book.officialPdfUrl,
        chapterCount: book.chapterCount,
        chaptersJson: JSON.stringify(book.chapters),
        sourceName: 'NCERT',
        sourceType: 'OFFICIAL',
        sourceVerifiedAt: new Date(),
        isActive: true,
      },
      create: {
        classNumber: book.classNumber,
        subject: book.subject,
        bookName: book.bookName,
        bookNameHi: book.bookNameHi,
        slug: book.slug,
        language: book.language,
        medium: book.medium,
        edition: book.edition,
        academicYear: book.academicYear,
        bookCode: book.bookCode,
        coverImageUrl: book.coverImageUrl,
        officialPageUrl: book.officialPageUrl,
        officialPdfUrl: book.officialPdfUrl,
        chapterCount: book.chapterCount,
        chaptersJson: JSON.stringify(book.chapters),
        sourceName: 'NCERT',
        sourceType: 'OFFICIAL',
        sourceVerifiedAt: new Date(),
        isActive: true,
      },
    });
    count++;
  }

  console.log(`✅ Successfully seeded/updated ${count} official NCERT textbooks in PostgreSQL.`);
  return count;
}

if (require.main === module) {
  seedNcertCatalog()
    .catch((err) => {
      console.error('Error seeding NCERT catalogue:', err);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
